# GitHub Sponsors configuration for Coercive Control Analysis
# Support this important social impact project

# GitHub Sponsors username
github: Carlymarie992

# Alternative funding platforms
ko_fi: # Add your Ko-fi username here if available
custom: 
  - "https://www.paypal.me/carlymarie992" # PayPal for direct donations
  - "mailto:cmcheney92@gmail.com?subject=Partnership%20Inquiry" # Email for organizational partnerships
