name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - Carlymarie992

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a feature!
        
        Your ideas help make this tool more effective for supporting those affected by coercive control.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: What would you like to be added or changed?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve and who would benefit
      placeholder: |
        - Who would use this feature? (e.g., researchers, support organizations, individuals)
        - What problem does it solve?
        - How would it improve the tool?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your ideal implementation

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternative approaches you've thought about

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of enhancement is this?
      options:
        - New analysis capability
        - New platform/format support
        - UI/UX improvement
        - Performance improvement
        - Security/Privacy enhancement
        - Documentation improvement
        - API enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Essential for project mission
        - High - Significantly improves functionality
        - Medium - Nice to have enhancement
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: privacy-security
    attributes:
      label: Privacy & Security Considerations
      description: Are there any privacy or security implications?
      placeholder: Describe any privacy or security considerations for this feature

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Technical approach or implementation suggestions (optional)
      placeholder: If you have technical ideas about implementation, share them here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add mockups, examples from other tools, or research links

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and pull requests to avoid duplicates
          required: true
        - label: This feature aligns with the project's mission of supporting those affected by coercive control
          required: true
        - label: I have considered privacy and security implications
          required: true
