name: 🔒 Security Vulnerability
description: Report a security vulnerability (confidential)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - Carlymarie992

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT - Responsible Disclosure
        
        Thank you for helping keep this project secure!
        
        **For severe vulnerabilities**, please consider using:
        - **Email**: cmcheney92@gmail.com (Subject: "SECURITY - Vulnerability Report")
        - **GitHub Security Advisory**: Use the "Security" tab → "Report a vulnerability"
        
        This ensures sensitive security information is not publicly disclosed before a fix is available.
        
        **Note**: This issue will be made public once the vulnerability is addressed.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical - Remote code execution, data breach, or complete system compromise
        - High - Significant security impact, privilege escalation
        - Medium - Limited security impact, requires user interaction
        - Low - Minor security issue or best practice violation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear description of the security vulnerability
      placeholder: What is the vulnerability?
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - Data exposure / Privacy leak
        - Authentication/Authorization bypass
        - Code injection (SQL, command, etc.)
        - Cross-Site Scripting (XSS)
        - Path traversal / File access
        - Insecure cryptography
        - Dependency vulnerability
        - Information disclosure
        - Denial of Service
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What could an attacker do? What data or systems are at risk?
      placeholder: |
        - What could be compromised?
        - What data could be exposed?
        - What actions could an attacker perform?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        1. Configure the system with...
        2. Execute command/request...
        3. Observe vulnerability...
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the codebase are affected?
      placeholder: |
        - Files: [e.g., encryption.py, data_processor.py]
        - Functions: [e.g., encrypt_file(), process_data()]
        - Versions: [e.g., all versions, v1.0.x]
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where is this vulnerability present?
      value: |
        - OS: 
        - Python Version: 
        - Installation Method: 
        - Version/Commit: 
    validations:
      required: true

  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed Fix (Optional)
      description: If you have ideas for how to fix this vulnerability
      placeholder: Describe potential solutions or mitigations

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant security advisories, CVEs, or documentation
      placeholder: |
        - CVE: 
        - Related advisories: 
        - Documentation: 

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional details, proof-of-concept code, etc.

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure Agreement
      options:
        - label: I agree to allow reasonable time for the vulnerability to be fixed before public disclosure
          required: true
        - label: I have not publicly disclosed this vulnerability elsewhere
          required: true
        - label: I understand this issue may be made private during investigation
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## What Happens Next?
        
        1. **Acknowledgment**: We will acknowledge receipt within 48 hours
        2. **Investigation**: We will investigate and validate the vulnerability
        3. **Fix Development**: We will develop and test a fix
        4. **Release**: We will release a security patch
        5. **Disclosure**: We will coordinate public disclosure with you
        
        **Thank you for helping keep this project secure!**
